version: "3.8"
services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_challenge
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Servicio del backend (Node.js)
  app:
    build: .
    container_name: api-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=api_challenge
    depends_on:
      - db 
    volumes:
      - .:/app
    command: npx ts-node src/index.ts

  # Servicio para Swagger UI
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/swagger.json
    depends_on:
      - app
    volumes:
      - ./swagger.json:/app/swagger.json

volumes:
  db_data:
